name: great_places_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5

  # Network
  http: ^0.13.5

  # Data Management
  sqflite: ^2.2.4+1

  # State Management
  provider: ^6.0.5
  path_provider: ^2.0.12

  # Utility
  image_picker: ^0.8.6+1
  path: ^1.8.2
  uuid: ^3.0.7
  location: ^4.4.0
  google_maps_flutter: ^2.2.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
